-- no cover image for now - will use default cover image
--INSERT INTO books (id, title, description, publisher, published_date, isbn, external_id) VALUES
--(1, 'The Great Gatsby', 'desc for great gatsby', 'Scribner', '1925-04-10', '9780743273565', '9780743273565'),
--(2, 'To Kill a Mockingbird', 'desc for mocking bird', 'J.B. Lippincott & Co.', '1960-07-11', '9780061120084', '9780061120084'),
--(3, '1984', 'desc for 1984', 'Secker & Warburg', '1949-06-08', '9780451524935', '9780451524935'),
--(4, 'The Catcher in the Rye', 'desc for The Catcher in the Rye', 'Little, Brown and Company', '1951-07-16', '9780316769488', '9780316769488'),
--(5, 'The Grapes of Wrath', 'desc for grapes', 'The Viking Press', '1939-04-14', '9780143039433', '9780143039433');

-- copy data from books_data.csv
-- COPY books (title, description, cover_image_small, cover_image_medium, publisher, published_year,isbn,number_of_pages,external_id)
-- FROM '/books_data.csv' DELIMITER ',' CSV HEADER;

-- COPY books (title, description, cover_image_small, cover_image_medium, publisher, published_year,isbn,number_of_pages,external_id)
-- FROM '/Users/joy/lighthouse/bookshelf/back-end/bin/books_data.csv' DELIMITER ',' CSV HEADER;
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Norton Anthology of English Literature','Collects literature written by the most well-known English authors.','https://covers.openlibrary.org/b/id/12483786-S.jpg','https://covers.openlibrary.org/b/id/12483786-M.jpg','Norton & Company, Incorporated, W. W.',1962,'0393985210',2686,'/works/OL2026379W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Poetics','One of the first books written on what is now called aesthetics. Although parts are lost (e.g., comedy), it has been very influential in western thought, such as the part on tragedy.','https://covers.openlibrary.org/b/id/6528920-S.jpg','https://covers.openlibrary.org/b/id/6528920-M.jpg','Ginn and Company',1536,'0672601680',128,'/works/OL13703833W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Histories','One of the earliest histories of the western world still extant, this gives a contemporary account of the Greco-Persian wars of the fifth century BCE with the rise of the Achaemenid Empire under Cyrus the Great.','https://covers.openlibrary.org/b/id/6366973-S.jpg','https://covers.openlibrary.org/b/id/6366973-M.jpg','Ekdoseis Gkovostē',1494,'0836999134',562,'/works/OL15678068W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Metamorphoses','The Metamorphoses is a narrative poem penned by the Roman poet Ovid. Widely considered to be his ultimate work, comprising fifteen books and over 250 myths. The poem portrays a history of the world from creation up to the deification of Julius Caesar. Metamorphoses is viewed as one of the most influential works in Western culture, inspiring authors such as Dante, Shakespeare, Chaucer, and Boccaccio. It has also inspired countless works of art from various artists throughout the centuries.','https://covers.openlibrary.org/b/id/7212118-S.jpg','https://covers.openlibrary.org/b/id/7212118-M.jpg','Printed by J. Exshaw',1479,'9781101180167',393,'/works/OL15292640W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Goodnight Moon','Goodnight to each of the objects in the great green room: goodnight chairs, goodnight comb, goodnight air.','https://covers.openlibrary.org/b/id/35556-S.jpg','https://covers.openlibrary.org/b/id/35556-M.jpg','HarperCollins]',1947,'0060541792',32,'/works/OL151798W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Prophet','Reflections by the Lebanese-American poet, mystic, and painter on such subjects as love, marriage, joy and sorrow, crime and punishment, pain, and self-knowlege.','https://covers.openlibrary.org/b/id/418324-S.jpg','https://covers.openlibrary.org/b/id/418324-M.jpg','Aims Intl Books Corp',1900,'2909611108',107,'/works/OL318900W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Matilda','Matilda es una ávida lectora de solo cinco años. Sensible e inteligente, todos la admiran menos sus mediocres padres, que la consideran una inútil. Además, tiene poderes extraños y maravillosos ... Un día, Matilda decide liberarse y empieza a emplearlos contra la abominable y cruel señorita Trunchbull.

Matilda is a sweet, exceptional young girl, but her parents think she''s just a nuisance. She expects school to be different but there she has to face Miss Trunchbull, a kid-hating terror of a headmistress. When Matilda is attacked by the Trunchbull she suddenly discovers she has a remarkable power with which to fight back. It''ll take a superhuman genius to give Miss Trunchbull what she deserves and Matilda may be just the one to do it!','https://covers.openlibrary.org/b/id/12889769-S.jpg','https://covers.openlibrary.org/b/id/12889769-M.jpg','Can Yayınları',1988,'0141361603',240,'/works/OL45846W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Dune','Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the "spice" melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for...

When House Atreides is betrayed, the destruction of Paul''s family will set the boy on a journey toward a destiny greater than he could ever have imagined. And as he evolves into the mysterious man known as Muad''Dib, he will bring to fruition humankind''s most ancient and unattainable dream.

A stunning blend of adventure and mysticism, environmentalism and politics, Dune won the first Nebula Award, shared the Hugo Award, and formed the basis of what is undoubtedly the grandest epic in science fiction.','https://covers.openlibrary.org/b/id/11481354-S.jpg','https://covers.openlibrary.org/b/id/11481354-M.jpg','Turtleback Books',1965,'0426038916',544,'/works/OL893415W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Pearl','A novel.','https://covers.openlibrary.org/b/id/9292332-S.jpg','https://covers.openlibrary.org/b/id/9292332-M.jpg','Em. Querido''s Uitgeverij',1945,'078873122X',118,'/works/OL7966242W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Inferno','Dante, after becoming lost on the path of life, is led by Virgil into Hell to begin his journey back to the light of God.','https://covers.openlibrary.org/b/id/6387077-S.jpg','https://covers.openlibrary.org/b/id/6387077-M.jpg','NYRB Classics',1782,'9780500013663',309,'/works/OL93227W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Utopia','First published in 1516, Thomas More''s Utopia is one of the most important works of European humanism. Through the voice of the mysterious traveler Raphael Hythloday, More describes a pagan, communist city-state governed by reason. Addressing such issues as religious pluralism, women''s rights, state-sponsored education, colonialism, and justified warfare, Utopia seems remarkably contemporary nearly five centuries after it was written, and it remains a foundational text in philosophy and political theory.','https://covers.openlibrary.org/b/id/7222976-S.jpg','https://covers.openlibrary.org/b/id/7222976-M.jpg','apud Corn. ab Egmond et socios',1518,'9781576467961',176,'/works/OL15366912W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Animal Farm','Animal Farm is an allegorical and dystopian novella by George Orwell, first published in England on 17 August 1945. According to Orwell, the book reflects events leading up to the Russian Revolution of 1917 and then on into the Stalinist era of the Soviet Union. Orwell, a democratic socialist, was a critic of Joseph Stalin and hostile to Moscow-directed Stalinism, an attitude that was critically shaped by his experiences during the Spanish Civil War. The Soviet Union, he believed, had become a brutal dictatorship, built upon a cult of personality and enforced by a reigh of terror. In a letter to Yvonne Davet, Orwell described Animal Farm as a satirical tale against Stalin (''un conte satirique contre Staline''), and in his essay ''Why I Write'' (1946), wrote that Animal Farm was the first book in which he tried, with full consciousness of what he was doing, ''to fuse political purpose and artistic purpose into one whole''. -- back cover','https://covers.openlibrary.org/b/id/11261770-S.jpg','https://covers.openlibrary.org/b/id/11261770-M.jpg','Independently published',1945,'9781652775980',130,'/works/OL1168007W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Siddhartha','Novel based on the life of a Brāhmaṇa Siddhārtha, contemporary of Gautama Buddha.','https://covers.openlibrary.org/b/id/6562535-S.jpg','https://covers.openlibrary.org/b/id/6562535-M.jpg','Media Rodzina',1922,'1570629706',141,'/works/OL872932W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Dracula','An annotated edition of Bram Stoker''s classic novel in which a small group of people, having discovered the double identity of the wealthy Transylvanian nobleman, Count Dracula, vow to rid the world of the evil vampire. Includes 1,500 notes, illustrations, character profiles, and an introduction by Neil Gaiman.','https://covers.openlibrary.org/b/id/12216503-S.jpg','https://covers.openlibrary.org/b/id/12216503-M.jpg','Distal',1897,'9780312241704',408,'/works/OL85892W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Bell Jar','The Bell Jar is the only novel written by American poet Sylvia Plath. It is an intensely realistic and emotional record of a successful and talented young woman''s descent into madness.','https://covers.openlibrary.org/b/id/8477115-S.jpg','https://covers.openlibrary.org/b/id/8477115-M.jpg','Can Yayınları',1963,'9798365576001',258,'/works/OL1865528W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Mrs. Dalloway','Virginia Woolf’s novel chronicles a day in the life of Clarissa Dalloway, a politician’s wife in 1920s London, as she prepares to host a party that evening. The narrative follows Clarissa’s thoughts (and sometimes those of people she meets) as she goes about her errands, and events in the day remind her of her youth and friendships from the past. As the book progresses characters from the past emerge, igniting old feelings and making Clarissa question the life she has created for herself.

Mrs. Dalloway became the inspiration for Michael Cunningham’s 1998 novel The Hours.','https://covers.openlibrary.org/b/id/6397580-S.jpg','https://covers.openlibrary.org/b/id/6397580-M.jpg','LUMEN',1925,'9781798966921',224,'/works/OL39349W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('La chute','Albert Camus, in his first work of fiction after The Plague, chose a subject eminently worthy of his supreme gifts: the conscience of modern man in the face of evil. Masterful in style and form, the narrative of The Fall is at once elegant, mordandt, brilliant with aphorism and paradox.

In a shady bar in Amsterdam, the man who does the talking in The Fall is indulging in a calculated confession. he recalls his past life as a respected Parisian lawyer, a pleader of noble causes, secure in his self-esteem, privately a libertine, yet apparently immune to judgement - the portrait of a modern Man. The irony of the recital predicts the downfall. Inescapable, it comes in the narrator''s intense discovery, in the space of one terrible and unforgettable instant, that no man is innocent and no man may therefore judge others from a standpoint of righteousness.','https://covers.openlibrary.org/b/id/8296477-S.jpg','https://covers.openlibrary.org/b/id/8296477-M.jpg','Knopf',1917,'9780241901717',147,'/works/OL1230631W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Scarlet Letter','A stark and allegorical tale of adultery, guilt, and social repression in Puritan New England, The Scarlet Letter is a foundational work of American literature. Nathaniel Hawthorne''s exploration of the dichotomy between the public and private self, internal passion and external convention, gives us the unforgettable Hester Prynne, who discovers strength in the face of ostracism and emerges as a heroine ahead of her time.','https://covers.openlibrary.org/b/id/5654516-S.jpg','https://covers.openlibrary.org/b/id/5654516-M.jpg','Econo-Clad Books',1850,'0671481711',288,'/works/OL455305W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Moonstone','One of the first English detective novels, this mystery involves the disappearance of a valuable diamond, originally stolen from a Hindu idol, given to a young woman on her eighteenth birthday, and then stolen again. A classic of 19th-century literature.','https://covers.openlibrary.org/b/id/8237041-S.jpg','https://covers.openlibrary.org/b/id/8237041-M.jpg','Independently published',1868,'173138274X',496,'/works/OL176092W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Great Expectations','Great Expectations is the thirteenth novel by Charles Dickens and his penultimate completed novel. It depicts the education of an orphan nicknamed Pip (the book is a bildungsroman; a coming-of-age story). It is Dickens'' second novel, after David Copperfield, to be fully narrated in the first person. The novel was first published as a serial in Dickens''s weekly periodical All the Year Round, from 1 December 1860 to August 1861. In October 1861, Chapman and Hall published the novel in three volumes.

The novel is set in Kent and London in the early to mid-19th century and contains some of Dickens''s most celebrated scenes, starting in a graveyard, where the young Pip is accosted by the escaped convict Abel Magwitch. Great Expectations is full of extreme imagery – poverty, prison ships and chains, and fights to the death – and has a colourful cast of characters who have entered popular culture. These include the eccentric Miss Havisham, the beautiful but cold Estella, and Joe, the unsophisticated and kind blacksmith. Dickens''s themes include wealth and poverty, love and rejection, and the eventual triumph of good over evil. Great Expectations, which is popular both with readers and literary critics, has been translated into many languages and adapted numerous times into various media.','https://covers.openlibrary.org/b/id/13322313-S.jpg','https://covers.openlibrary.org/b/id/13322313-M.jpg','Tor',1861,'9798466012767',493,'/works/OL8721462W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('King Solomon''s Mines','Promoted as “the most amazing book ever written,” King Solomon’s Mines enjoyed lavish success. As far as adventure stories go, this classic tale of English travelers who discover a lost African kingdom rivals Treasure Island.','https://covers.openlibrary.org/b/id/6861197-S.jpg','https://covers.openlibrary.org/b/id/6861197-M.jpg','Reader''s Digest',1885,'9781855345065',256,'/works/OL17449W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Macbeth','Presents the play with supporting material, explanation of words and phrases, actors'' and directors'' views, study questions, etc.','https://covers.openlibrary.org/b/id/872432-S.jpg','https://covers.openlibrary.org/b/id/872432-M.jpg','Galaxia',1508,'0713181052',139,'/works/OL258902W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Rebecca','Is Rebecca really dead? Her insidious influence seems to extend beyond the grave!','https://covers.openlibrary.org/b/id/8238729-S.jpg','https://covers.openlibrary.org/b/id/8238729-M.jpg','Edicions 62',1737,'0606044922',399,'/works/OL36633W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Canterbury Tales','A collection of stories written in Middle English by Geoffrey Chaucer at the end of the 14th century. The tales (mostly in verse, although some are in prose) are told as part of a story-telling contest by a group of pilgrims as they travel together on a journey from Southwark to the shrine of Saint Thomas Becket at Canterbury Cathedral. In a long list of works, including Troilus and Criseyde, House of Fame, and Parliament of Fowls, The Canterbury Tales was Chaucer''s magnum opus. He uses the tales and the descriptions of the characters to paint an ironic and critical portrait of English society at the time, and particularly of the Church. Structurally, the collection bears the influence of The Decameron, which Chaucer is said to have come across during his first diplomatic mission to Italy in 1372. However, Chaucer peoples his tales with ''sondry folk'' rather than Boccaccio''s fleeing nobles.','https://covers.openlibrary.org/b/id/5767180-S.jpg','https://covers.openlibrary.org/b/id/5767180-M.jpg','George Routledge',1478,'0340185015',332,'/works/OL531767W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Faust','Faust is a tragic play in two parts by Johann Wolfgang von Goethe, usually known in English as Faust, Part One and Faust, Part Two. Nearly all of Part One and the majority of Part Two are written in rhymed verse.','https://covers.openlibrary.org/b/id/6499459-S.jpg','https://covers.openlibrary.org/b/id/6499459-M.jpg','Henniger',1800,'9783442075928',306,'/works/OL52456W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Ethan Frome','Ethan Frome toils at his New Enoland farm while struggling to maintain a bearable existence with his sickly and judgemental wife, Zeena. He finds himself increasingly drawn to Mattie, Zeena''s cousin, who helps around the house. Although she represents the possibility of happiness, they are trapped by their hopeless situation. And when Zeena becomes suspicious and arranges for Mattie to be sent away, events take a tragic turn.

This heart-breaking portrait, from the author of The House of Mirth, is an intimate look at choices not made and lives not yet lived. First published in 1911 and adapted for film, Ethan Frome remains for many the most subtle and moving of Wharton''s works.','https://covers.openlibrary.org/b/id/8303480-S.jpg','https://covers.openlibrary.org/b/id/8303480-M.jpg','Jin ri shi jie she',1910,'1987686551',98,'/works/OL98501W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Ugly Duckling','An ugly and unloved duckling turns out to be a beautiful swan.','https://covers.openlibrary.org/b/id/446546-S.jpg','https://covers.openlibrary.org/b/id/446546-M.jpg','Childs World',1851,'9781474791526',32,'/works/OL15155002W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Death on the Nile','The tranquillity of a cruise along the Nile was shattered by the discovery that Linnet Ridgeway ( Linnet Doyle) had been shot through the head. She was young, stylish, rich and beautiful. A girl who had everything... until she lost her life.

Hercule Poirot recalled an earlier outburst by a fellow passenger: ''I''d like to put my dear little pistol against her head and just press the trigger.'' Yet in this exotic setting nothing was ever quite what it seemed...','https://covers.openlibrary.org/b/id/10746221-S.jpg','https://covers.openlibrary.org/b/id/10746221-M.jpg','Dodd, Mead & company',1937,'0007234473',287,'/works/OL471724W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Jane Eyre','The novel is set somewhere in the north of England. Jane''s childhood at Gateshead Hall, where she is emotionally and physically abused by her aunt and cousins; her education at Lowood School, where she acquires friends and role models but also suffers privations and oppression; her time as the governess of Thornfield Hall, where she falls in love with her Byronic employer, Edward Rochester; her time with the Rivers family, during which her earnest but cold clergyman cousin, St John Rivers, proposes to her. Will she or will she not marry him?','https://covers.openlibrary.org/b/id/8235363-S.jpg','https://covers.openlibrary.org/b/id/8235363-M.jpg','Aims Intl Books Corp',1847,'1503278190',496,'/works/OL1095427W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Prince','The Prince (Italian: Il Principe [il ˈprintʃipe]; Latin: De Principatibus) is a 16th-century political treatise written by Italian diplomat and political theorist Niccolò Machiavelli as an instruction guide for new princes and royals. The general theme of The Prince is of accepting that the aims of princes – such as glory and survival – can justify the use of immoral means to achieve those ends.

From Machiavelli''s correspondence, a version appears to have been distributed in 1513, using a Latin title, De Principatibus (Of Principalities). However, the printed version was not published until 1532, five years after Machiavelli''s death. This was carried out with the permission of the Medici pope Clement VII, but "long before then, in fact since the first appearance of The Prince in manuscript, controversy had swirled about his writings".

Although The Prince was written as if it were a traditional work in the mirrors for princes style, it was generally agreed as being especially innovative. This is partly because it was written in the vernacular Italian rather than Latin, a practice that had become increasingly popular since the publication of Dante''s Divine Comedy and other works of Renaissance literature.','https://covers.openlibrary.org/b/id/12726168-S.jpg','https://covers.openlibrary.org/b/id/12726168-M.jpg','Ediotes Mexicanos Unidos',1515,'155445428X',153,'/works/OL1089297W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Anna Karenina','Anna Karenina tells of the doomed love affair between the sensuous and rebellious Anna and the dashing officer, Count Vronsky. Tragedy unfolds as Anna rejects her passionless marriage and must endure the hypocrisies of society. Set against a vast and richly textured canvas of nineteenth-century Russia, the novel''s seven major characters create a dynamic imbalance, playing out the contrasts of city and country life and all the variations on love and family happiness. While previous versions have softened the robust, and sometimes shocking, quality of Tolstoy''s writing, Pevear and Volokhonsky have produced a translation true to his powerful voice. This award-winning team''s authoritative edition also includes an illuminating introduction and explanatory notes. Beautiful, vigorous, and eminently readable, this Anna Karenina will be the definitive text for generations to come.','https://covers.openlibrary.org/b/id/2560652-S.jpg','https://covers.openlibrary.org/b/id/2560652-M.jpg','Oxford Univ Pr',1876,'9781094015286',837,'/works/OL267096W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Decamerone','ENTERTAINING ROMANTIC STORIES OF YOUNG MEN AND WOMEN FLEEING THE BLACK DEATH IN ITALY AND, AS A RESULT, TAKE TURNS TELLING ROMANTIC STORIES EACH EVENING DURING THEIR 10 DAY FLIGHT.','https://covers.openlibrary.org/b/id/6073528-S.jpg','https://covers.openlibrary.org/b/id/6073528-M.jpg','Bibliophilist Society',1516,'9991087079',574,'/works/OL7180368W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Sayings of Lao Tzü','Eighty-one poems constituting an Eastern classic, the mystical and moral teachings of which bring a message of living simply, finding contentment with a minimum of comfort, and prizing culture above all else.','https://covers.openlibrary.org/b/id/10857861-S.jpg','https://covers.openlibrary.org/b/id/10857861-M.jpg','Văn Hóa',1875,'9781101143018',165,'/works/OL45503W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Art of War','The Art of War (Chinese: 孫子兵法; lit. ''Sun Tzu''s Military Method'') is traditionally ascribed to Sun Tzu. It presents a philosophy of war for managing conflicts and winning battles. It is accepted as a masterpiece on strategy and has been frequently cited and referred to by generals and theorists since it was first published, translated, and distributed internationally.','https://covers.openlibrary.org/b/id/671290-S.jpg','https://covers.openlibrary.org/b/id/671290-M.jpg','Adams Media Corporation',1910,'1929194005',186,'/works/OL278851W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Anne of Avonlea','In this sequel to Anne of Green Gables, teenaged Anne Shirley becomes a schoolteacher in a small village on Prince Edward Island.','https://covers.openlibrary.org/b/id/8237948-S.jpg','https://covers.openlibrary.org/b/id/8237948-M.jpg','Ren Kitap',1909,'1695144112',310,'/works/OL272228W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('A Room of One''s Own','Why is it that men, and not women, have always had power, wealth, and fame? Woolf cites the two keys to freedom: fixed income and one''s own room.','https://covers.openlibrary.org/b/id/6559057-S.jpg','https://covers.openlibrary.org/b/id/6559057-M.jpg','Alianza',1929,'1070421154',141,'/works/OL39379W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Flatland','Flatland: A Romance of Many Dimensions, though written in 1884, is still considered useful in thinking about multiple dimensions. It is also seen as a satirical depiction of Victorian society and its hierarchies. A square, who is a resident of the two-dimensional Flatland, dreams of the one-dimensional Lineland. He attempts to convince the monarch of Lineland of the possibility of another dimension, but the monarch cannot see outside the line. The square is then visited himself by a Sphere from three-dimensional Spaceland, who must show the square Spaceland before he can conceive it. As more dimensions enter the scene, the story''s discussion of fixed thought and the kind of inhuman action which accompanies it intensifies.','https://covers.openlibrary.org/b/id/10069547-S.jpg','https://covers.openlibrary.org/b/id/10069547-M.jpg','Independently published',1884,'1795720719',114,'/works/OL118388W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Phantastes','One of George MacDonald''s most important works, Phantastes is the story of a young man named Anotos and his long dreamlike journey in Fairy Land. It is the fairy tale of deep spiritual insight as Anotos makes his way through moments of uncertainty and peril and mistakes that can have irreversible consequences. This is also his spiritual quest that is destined to end with the supreme surrender of the self. When he finally experiences the hard-won surrender, a wave of joy overwhelms him. His intense personal introspection is honest as he is offered the full range of symbolic choices--great beauty, horrifying ugliness, irritating goblins, nurturing spirits. Each confrontation in Fairy Land allows Anotos to learn many necessary lessons. As he continues on the journey, many shadowy beings threaten his spiritual well-being and compel him to sing. The songs are irresistible to a beautiful White Lady who is freed from inside a statue by the music, and Anotos remains captivated by her for a long time. He sees the world more objectively; his trek invites a natural descent into feelings of pride and egotism. But his losses and sorrows coalesce themselves into things of grace, and these experiences help his spiritual growth. Please Note: This book has been reformatted to be easy to read in true text, not scanned images that can sometimes be difficult to decipher. The Microsoft eBook has a contents page linked to the chapter headings for easy navigation. The Adobe eBook has bookmarks at chapter headings and is printable up to two full copies per year. Both versions are text searchable.','https://covers.openlibrary.org/b/id/14358814-S.jpg','https://covers.openlibrary.org/b/id/14358814-M.jpg','RosettaBooks',1850,'0802860605',197,'/works/OL15450W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Ivanhoe','The father of the historical novel, Sir Walter Scott invented a literary form that has remained popular for over one hundred and fifty years. Infusing his works with romance, action, and suspense, he brought long-gone eras back to life with splendor and spectacle.Set in England just after the Third Crusade, Ivanhoe is the tale of Wilfrid, a young Saxon knight, and his love for the royal princess Rowena. With his father against their union, Wilfrid embarks on a series of adventures to prove his worth, finding himself in conflict against the Normans and the Templars, and allied with such larger-than-life figures as Robin Hood and Richard the Lion Hearted. A timeless story of courage, chivalry, and courtly love, Ivanhoe is a grand epic, and its place in classical literature is assured.','https://covers.openlibrary.org/b/id/314235-S.jpg','https://covers.openlibrary.org/b/id/314235-M.jpg','Amsco School Pubns Inc',1800,'8432069752',498,'/works/OL863808W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Moonstone','One of the first English detective novels, this mystery involves the disappearance of a valuable diamond, originally stolen from a Hindu idol, given to a young woman on her eighteenth birthday, and then stolen again. A classic of 19th-century literature.','https://covers.openlibrary.org/b/id/8237041-S.jpg','https://covers.openlibrary.org/b/id/8237041-M.jpg','Independently published',1868,'173138274X',496,'/works/OL176092W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Blithedale Romance','Presents an annotated edition of Hawthorne''s novel based on the Brook Farm socialistic experiment which George Ripley started in 1841 with the help of fellow Transcendentalists; and includes a selection of background and source material, and critical essays.','https://covers.openlibrary.org/b/id/8245179-S.jpg','https://covers.openlibrary.org/b/id/8245179-M.jpg','Turtleback Books Distributed by Demco Media',1852,'0393091503',258,'/works/OL455512W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Tender is the Night','A psychiatrist, Dick Diver, treats and eventually marries a wealthy patient, Nicole. Eventually, this marriage destroys him.','https://covers.openlibrary.org/b/id/6984433-S.jpg','https://covers.openlibrary.org/b/id/6984433-M.jpg','Aims Intl Books Corp',1933,'9781907360299',352,'/works/OL468485W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Invisible Man','This book is the story of Griffin, a scientist who creates a serum to render himself invisible, and his descent into madness that follows.','https://covers.openlibrary.org/b/id/6419199-S.jpg','https://covers.openlibrary.org/b/id/6419199-M.jpg','Anaya',1897,'9996444678',182,'/works/OL52266W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Blue Castle','In early 1920s Canada, drastic circumstances give Valancy, a twenty-nine-year-old unmarried woman resigned to being an "old maid," the courage to defy her controlling family and escape to a life of her own choosing.','https://covers.openlibrary.org/b/id/369039-S.jpg','https://covers.openlibrary.org/b/id/369039-M.jpg','Independently published',1926,'9798523720123',257,'/works/OL77775W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('When the Sleeper Awakes','A troubled insomniac in 1890s England falls suddenly into a sleep-like trance, from which he does not awake for over two hundred years. During his centuries of slumber, however, investments are made that make him the richest and most powerful man on Earth. But when he comes out of his trance he is horrified to discover that the money accumulated in his name is being used to maintain a hierarchal society in which most are poor, and more than a third of all people are enslaved. Oppressed and uneducated, the masses cling desperately to one dream – that the sleeper will awake, and lead them all to freedom.','https://covers.openlibrary.org/b/id/574886-S.jpg','https://covers.openlibrary.org/b/id/574886-M.jpg','Charles E. Tuttle',1899,'1846375169',278,'/works/OL52151W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Last Man','It is the twenty-first century, and England is a republic governed by a ruling elite, one of whom, Adrian, Earl of Windsor, has introduced a Cumbrian boy to the circle. This outsider, Lionel Verney, narrates, a tale of complicated, tragic love, and of the gradual extermination of the human race by plague.','https://covers.openlibrary.org/b/id/882662-S.jpg','https://covers.openlibrary.org/b/id/882662-M.jpg','Gray Rabbit Publications',1826,'9781689922487',414,'/works/OL450124W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Handmaid''s Tale','Offred is a Handmaid in the Republic of Gilead. She may leave the home of the Commander and his wife once a day to walk to food markets whose signs are now pictures instead of words because women are no longer allowed to read. She must lie on her back once a month and pray that the Commander makes her pregnant, because in an age of declining births, Offred and the other Handmaids are valued only if their ovaries are viable. Offred can remember the years before, when she lived and made love with her husband, Luke; when she played with and protected her daughter; when she had a job, money of her own, and access to knowledge. But all of that is gone now...','https://covers.openlibrary.org/b/id/8231851-S.jpg','https://covers.openlibrary.org/b/id/8231851-M.jpg','Ghoghnoos Publishing',1985,'8498388015',350,'/works/OL675783W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Giver','Given his lifetime assignment at the Ceremony of Twelve, Jonas becomes the receiver of memories shared by only one other in his community and discovers the terrible truth about the society in which he liv','https://covers.openlibrary.org/b/id/8352502-S.jpg','https://covers.openlibrary.org/b/id/8352502-M.jpg','Turtleback Books',1993,'0613047923',200,'/works/OL1846076W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Anthem','Novel; Individual versus the ultimate collective society.','https://covers.openlibrary.org/b/id/802982-S.jpg','https://covers.openlibrary.org/b/id/802982-M.jpg','Boomer Books',1936,'0451078462',97,'/works/OL731737W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Hunger Games','In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.

Sixteen-year-old Katniss Everdeen, who lives alone with her mother and younger sister, regards it as a death sentence when she steps forward to take her sister''s place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love.','https://covers.openlibrary.org/b/id/12646537-S.jpg','https://covers.openlibrary.org/b/id/12646537-M.jpg','Scholastic',2008,'1407157868',399,'/works/OL5735363W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('A Clockwork Orange','A Clockwork Orange is a dystopian satirical black comedy novel by English writer Anthony Burgess, published in 1962. It is set in a near-future society that has a youth subculture of extreme violence. The teenage protagonist, Alex, narrates his violent exploits and his experiences with state authorities intent on reforming him. The book is partially written in a Russian-influenced argot called "Nadsat", which takes its name from the Russian suffix that is equivalent to ''-teen'' in English. According to Burgess, it was a jeu d''esprit written in just three weeks.

In 2005, A Clockwork Orange was included on Time magazine''s list of the 100 best English-language novels written since 1923, and it was named by Modern Library and its readers as one of the 100 best English-language novels of the 20th century. The original manuscript of the book has been kept at McMaster University''s William Ready Division of Archives and Research Collections in Hamilton, Ontario, Canada since the institution purchased the documents in 1971. It is considered one of the most influential dystopian books.','https://covers.openlibrary.org/b/id/13151224-S.jpg','https://covers.openlibrary.org/b/id/13151224-M.jpg','Tandem Library',1962,'8499308465',192,'/works/OL261794W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Fahrenheit 451','Sixty years after its original publication, Ray Bradbury''s internationally acclaimed novel Fahrenheit 451 stands as a classic of world literature set in a bleak, dystopian future. Today its message has grown more relevent than ever before.

Guy Montag is a fireman. His job is to destroy the most illegal of commodoties, the printed book, along with the houses in which they are hidden. Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred, who spends all day with her television “family.” But then he meets an eccentric young neighbor, Clarisse, who introduces him to a past where people didn’t live in fear and to a present where one sees the world through the ideas in books instead of the mindless chatter of television, Montag begins to question everything he has ever known.

This sixtieth-anniversary edition commemorates Ray Bradbury''s masterpiece with a new introduction by Neil Baiman; personal essays on the genesis of the novel by the author; a wealth of critical essays and reviews by Nelson Algren. Harold Bloom, Margaret Atwood, and others: rare manuscript pages and sketches from "Ray Bradbury''s personal archive and much more. Here, at last, is the definitive edition of a classic of world literature.','https://covers.openlibrary.org/b/id/12993656-S.jpg','https://covers.openlibrary.org/b/id/12993656-M.jpg','Klett Schulbuch, Stgt.',1953,'9573322293',190,'/works/OL103123W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Brave New World','Originally published in 1932, this outstanding work of literature is more crucial and relevant today than ever before. Cloning, feel-good drugs, antiaging programs, and total social control through politics, programming, and media -- has Aldous Huxley accurately predicted our future? With a storyteller''s genius, he weaves these ethical controversies in a compelling narrative that dawns in the year 632 AF (After Ford, the deity). When Lenina and Bernard visit a savage reservation, we experience how Utopia can destroy humanity. A powerful work of speculative fiction that has enthralled and terrified readers for generations, Brave New World is both a warning to be heeded and thought-provoking yet satisfying entertainment. - Container.','https://covers.openlibrary.org/b/id/8231823-S.jpg','https://covers.openlibrary.org/b/id/8231823-M.jpg','Gui guan',1932,'1978200544',254,'/works/OL64468W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Foundation','One of the great masterworks of science fiction, the Foundation novels of Isaac Asimov are unsurpassed for their unique blend of nonstop action, daring ideas, and extensive world-building.

The story of our future begins with the history of Foundation and its greatest psychohistorian: Hari Seldon. For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. Only Hari Seldon, creator of the revolutionary science of psychohistory, can see into the future--a dark age of ignorance, barbarism, and warfare that will last thirty thousand years. To preserve knowledge and save mankind, Seldon gathers the best minds in the Empire--both scientists and scholars--and brings them to a bleak planet at the edge of the Galaxy to serve as a beacon of hope for future generations. He calls his sanctuary the Foundation.

But soon the fledgling Foundation finds itself at the mercy of corrupt warlords rising in the wake of the receding Empire. And mankind''s last best hope is faced with an agonizing choice: submit to the barbarians and live as slaves--or take a stand for freedom and risk total destruction.','https://covers.openlibrary.org/b/id/6501822-S.jpg','https://covers.openlibrary.org/b/id/6501822-M.jpg','HarperCollins Science Fiction & Fantasy',1951,'9781439507131',249,'/works/OL46125W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('I, Robot','Isaac Asimov''s I, Robot launches readers on an adventure into a not-so-distant future where man and machine , struggle to redefinelife, love, and consciousness—and where the stakes are nothing less than survival. Filled with unforgettable characters, mind-bending speculation, and nonstop action, I, Robot is a powerful reading experience from one of the master storytellers of our time.

I, ROBOT

They mustn''t harm a human being, they must obey hitman orders, and they must protect their own existence...but only so long as that doesn''t violate rules one and two. With these Three Laws of Robotics, humanity embarked on perhaps its greatest adventure: the invention of the first positronic man. It was a bold new era of evolution that would open up enormous possibilities—and unforeseen risks. For the scientists who invented the earliest robots weren''t content that their creations should '' remain programmed helpers, companions, and semisentient worker-machines. And soon the robots themselves; aware of their own intelligence, power, and humanity, aren''t either.

As humans and robots struggle to survive together—and sometimes against each other—on earth and in space, the future of both hangs in the balance. Human men and women confront robots gone mad, telepathic robots, robot politicians, and vast robotic intelligences that may already secretly control the world. And both are asking the same questions: What is human? And is humanity obsolete?

In l, Robot Isaac Asimov changes forever our perception of robots, and human beings and updates the timeless myth of man''s dream to play god. with all its rewards—and terrors.','https://covers.openlibrary.org/b/id/12385229-S.jpg','https://covers.openlibrary.org/b/id/12385229-M.jpg','Turtleback Books',1950,'9780739346273',224,'/works/OL46241W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Time Machine','The Time Traveller, a dreamer obsessed with traveling through time, builds himself a time machine and, much to his surprise, travels over 800,000 years into the future. He lands in the year 802701: the world has been transformed by a society living in apparent harmony and bliss, but as the Traveler stays in the future he discovers a hidden barbaric and depraved subterranean class. Wells''s transparent commentary on the capitalist society was an instant bestseller and launched the time-travel genre.','https://covers.openlibrary.org/b/id/9009316-S.jpg','https://covers.openlibrary.org/b/id/9009316-M.jpg','Hyde Park Editions Limited',1895,'9781978021303',120,'/works/OL52267W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('The Last Man','Mary Shelley, the author of Frankenstein, wrote the apocalyptic novel The Last Man in 1826. Its first person narrative tells the story of our world standing at the end of the twenty-first century and - after the devastating effects of a plague - at the end of humanity. In the book Shelley writes of weaving this story from a discovery of prophetic writings uncovered in a cave near Naples. The Last Man was made into a 2008 film.','https://covers.openlibrary.org/b/id/882662-S.jpg','https://covers.openlibrary.org/b/id/882662-M.jpg','Gray Rabbit Publications',1826,'9781689922487',414,'/works/OL450124W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Harry Potter and the Philosopher''s Stone','Harry Potter #1

When mysterious letters start arriving on his doorstep, Harry Potter has never heard of Hogwarts School of Witchcraft and Wizardry.

They are swiftly confiscated by his aunt and uncle.

Then, on Harry’s eleventh birthday, a strange man bursts in with some important news: Harry Potter is a wizard and has been awarded a place to study at Hogwarts.

And so the first of the Harry Potter adventures is set to begin.','https://covers.openlibrary.org/b/id/10521270-S.jpg','https://covers.openlibrary.org/b/id/10521270-M.jpg','der horverlag',1997,'0545790352',303,'/works/OL82563W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Harry Potter and the Deathly Hallows','Harry Potter is leaving Privet Drive for the last time. But as he climbs into the sidecar of Hagrid’s motorbike and they take to the skies, he knows Lord Voldemort and the Death Eaters will not be far behind.

The protective charm that has kept him safe until now is broken. But the Dark Lord is breathing fear into everything he loves. And he knows he can’t keep hiding.

To stop Voldemort, Harry knows he must find the remaining Horcruxes and destroy them.

He will have to face his enemy in one final battle.','https://covers.openlibrary.org/b/id/10110415-S.jpg','https://covers.openlibrary.org/b/id/10110415-M.jpg','Media Rodzina',2007,'3551557470',698,'/works/OL82586W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Harry Potter and the Order of the Phoenix','After the Dementors’ attack on his cousin Dudley, Harry knows he is about to become Voldemort’s next target.

Although many are denying the Dark Lord’s return, Harry is not alone, and a secret order is gathering at Grimmauld Place to fight against the Dark forces.

Meanwhile, Voldemort’s savage assaults on Harry’s mind are growing stronger every day.

He must allow Professor Snape to teach him to protect himself before he runs out of time.','https://covers.openlibrary.org/b/id/10523466-S.jpg','https://covers.openlibrary.org/b/id/10523466-M.jpg','Media Rodzina',2003,'8702022222',893,'/works/OL82548W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Harry Potter and the Prisoner of Azkaban','Harry Potter, along with his best friends, Ron and Hermione, is about to start his third year at Hogwarts School of Witchcraft and Wizardry. Harry can''t wait to get back to school after the summer holidays. (Who wouldn''t if they lived with the horrible Dursleys?) But when Harry gets to Hogwarts, the atmosphere is tense. There''s an escaped mass murderer on the loose, and the sinister prison guards of Azkaban have been called in to guard the school...','https://covers.openlibrary.org/b/id/10580435-S.jpg','https://covers.openlibrary.org/b/id/10580435-M.jpg','Bod ljongs mi dmangs spe skrun khang',1999,'9780329258405',416,'/works/OL82536W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Harry Potter and the Chamber of Secrets','The Dursleys were so mean and hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he''s packing his bags, Harry receives a warning from a strange, impish creature named Dobby who says that if Harry Potter returns to Hogwarts, disaster will strike

And strike it does. For in Harry''s second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor, Gilderoy Lockhart, a spirit named Moaning Myrtle who haunts the girls'' bathroom, and the unwanted attentions of Ron Weasley''s younger sister, Ginny.

But each of these seem minor annoyances when the real trouble begins, and someone -- or something -- starts turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possibly be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects . . . Harry Potter himself?','https://covers.openlibrary.org/b/id/8392798-S.jpg','https://covers.openlibrary.org/b/id/8392798-M.jpg','Der Hörverlag',1900,'0685116328',341,'/works/OL82537W');
INSERT INTO books(title,description,cover_image_small,cover_image_medium,publisher,published_year,isbn,number_of_pages,external_id) VALUES ('Harry Potter and the Half-Blood Prince','One summer night, when Dumbledore arrives at Privet Drive to collect Harry Potter, his wand hand is blackened and shriveled, but he will not reveal why.

Rumours and suspicion spread through the wizarding world – it feels as if even Hogwarts itself might be under threat.

Harry is convinced that Malfoy bears the Dark Mark: could there be a Death Eater amongst them?

He will need powerful magic and true friends as, with the help of Dumbledore, he investigates Voldemort’s darkest secrets','https://covers.openlibrary.org/b/id/10716273-S.jpg','https://covers.openlibrary.org/b/id/10716273-M.jpg','Der Hörverlag',2005,'9780828814522',652,'/works/OL82565W');
