--INSERT INTO authors (id, name) VALUES
--(1, 'F. Scott Fitzgerald'),
--(2, 'Harper Lee'),
--(3, 'George Orwell'),
--(4, 'J.D. Salinger'),
--(5, 'John Steinbeck');
INSERT INTO authors (name) VALUES
('M. H. Abrams'),
('Stephen Greenblatt'),
('Aristotle'),
('Leon Golden'),
('O. B. Hardison'),
('Herodotus'),
('Ovid'),
('Margaret Wise Brown'),
('Kahlil Gibran'),
('Roald Dahl'),
('Frank Herbert'),
('John Steinbeck'),
('Dante Alighieri'),
('Marcus Sanders'),
('Doug Harvey'),
('Thomas More'),
('Astrid Lindgren'),
('George Orwell'),
('Bram Stoker'),
('Sylvia Plath'),
('Virginia Woolf'),
('Albert Camus'),
('Nathaniel Hawthorne'),
('Wilkie Collins'),
('Pieter Koster'),
('Sandra Kemp'),
('Andronum'),
('Charles Dickens'),
('H. Rider Haggard'),
('William Shakespeare'),
('Daphne du Maurier'),
('Geoffrey Chaucer'),
('John E. Cunningham'),
('Johann Wolfgang von Goethe'),
('Edith Wharton'),
('Hans Christian Andersen'),
('Agatha Christie'),
('Charlotte Brontë'),
('Niccolò Machiavelli'),
('Lev Nikolaevič Tolstoy'),
('Giovanni Boccaccio'),
('Laozi'),
('Sun Tzu'),
('Lucy Maud Montgomery'),
('Virginia Woolf'),
('Edwin Abbott Abbot'),
('Monty'),
('Sajad Hussain'),
('Joel Dueck'),
('George MacDonald'),
('Sir Walter Scott'),
('Wilkie Collins'),
('Pieter Koster'),
('Sandra Kemp'),
('Andronum'),
('Nathaniel Hawthorne'),
('F. Scott Fitzgerald'),
('H. G. Wells'),
('Lucy Maud Montgomery'),
('H. G. Wells'),
('Mary Wollstonecraft Shelley'),
('Margaret Atwood'),
('Lois Lowry'),
('Ayn Rand'),
('Erin Bateman'),
('Suzanne Collins'),
('Anthony Burgess'),
('Ray Bradbury'),
('Aldous Huxley'),
('Isaac Asimov'),
('Rowena Akinyemi'),
('Tricia Reilly'),
('H. G. Wells'),
('Mary Wollstonecraft Shelley'),
('J. K. Rowling');
