INSERT INTO genres (name) VALUES
('English Literature'),
('American Literature'),
('Italian Literature'),
('French Literature'),
('German Literature'),
('Spanish Literature'),
('Asian Literature'),
('Fiction'),
('Historical'),
('Poetry'),
('Ancient and Classical'),
('Mythology'),
('Religion'),
('Childrens Stories'),
('Young Adult'),
('Romance'),
('Adventure'),
('Drama'),
('Mystery'),
('Magic'),
('Revenge'),
('Fantasy'),
('Dystopia'),
('Politics'),
('Time Travel'),
('Pyschological'),
('Science Fiction'),
('Suspense'),
('Tradegy'),
('Action'),
('Thriller'),
('Military Art and Science'),
('Feminism');