-- INSERT INTO reviews(user_id,book_id,rating,user_review) VALUES
-- (1,3,2,'This book was too deep for me and I lost interest.'),
-- (1,14,4,'I really enjoyed this book. It kept me on my toes and I really liked how the main character Dracula was personified in the story.'),
-- (1,34,5,'I did not think I would be interested in this book at all. But the tactical strategies and warfare plans really intrigued me.');

INSERT INTO reviews(user_id,book_author_id,rating,user_review) VALUES
(1, 76, 5, '"Harry Potter and the Philosopher''s Stone" by J.K. Rowling is an enchanting tale that whisks readers away to a world of magic, wonder, and adventure. From the moment we meet young Harry Potter, a seemingly ordinary boy with an extraordinary destiny, we are captivated by his journey of self-discovery and bravery. Rowling''s vivid imagination brings to life a richly detailed universe filled with memorable characters, captivating spells, and mysterious creatures. As Harry embarks on his first year at Hogwarts School of Witchcraft and Wizardry, he learns about friendship, loyalty, and the power of love. The story is masterfully woven with twists and turns, keeping readers on the edge of their seats until the very end. From facing down a three-headed dog to outsmarting a life-threatening chess game, Harry''s adventures are both thrilling and heartwarming. But beyond the magical escapades, "Harry Potter and the Philosopher''s Stone" touches on deeper themes of good versus evil, the importance of standing up for what is right, and the bonds of friendship that transcend differences. Overall, "Harry Potter and the Philosopher''s Stone" is a timeless classic that continues to captivate readers of all ages. Its magic lies not only in its fantastical elements but also in its poignant messages of courage, resilience, and the enduring power of love. It''s a must-read for anyone who believes in the magic of storytelling.'),
(1, 40, 5, '"Anna Karenina" by Leo Tolstoy is a timeless masterpiece that delves into the intricacies of human relationships, societal norms, and the pursuit of happiness. Set against the backdrop of 19th-century Russia, Tolstoy weaves a captivating tale of love, passion, and tragedy that resonates with readers even today. At the heart of the novel is the titular character, Anna Karenina, a woman torn between her duties as a wife and mother and her desires for passion and fulfillment. As she embarks on a forbidden affair with the dashing Count Vronsky, Anna grapples with the consequences of her actions and the societal condemnation that follows. Tolstoy''s rich character development and nuanced storytelling bring to life a cast of unforgettable characters, each grappling with their own desires, fears, and insecurities. From the idealistic Levin to the enigmatic Countess Lydia, the characters in "Anna Karenina" are complex and multi-dimensional, reflecting the complexities of the human condition. Beyond its compelling characters, "Anna Karenina" explores profound themes such as love, morality, and the search for meaning in life. Through Anna''s journey, Tolstoy raises questions about the nature of love, the role of society in dictating our actions, and the consequences of pursuing one''s desires at any cost. The novel''s vivid descriptions of Russian society and culture provide a rich backdrop against which the drama unfolds. From the opulent ballrooms of St. Petersburg to the sprawling estates of the Russian countryside, Tolstoy paints a vivid portrait of a society on the brink of change. In conclusion, "Anna Karenina" is a literary masterpiece that continues to captivate readers with its timeless themes, unforgettable characters, and masterful storytelling. Tolstoy''s exploration of love, morality, and human nature makes "Anna Karenina" a must-read for anyone seeking to delve into the depths of the human soul.'),
(1, 74, 4, 'H.G. Wells'' "The Time Machine" is a captivating journey through time that explores fascinating concepts and propels readers into a world of speculative fiction. The story follows an unnamed Time Traveller as he invents a machine capable of traversing the vast expanse of time. With meticulous detail, Wells paints a vivid picture of future societies and civilizations, each with its own unique characteristics and challenges. The narrative is rich with imaginative ideas and thought-provoking scenarios, inviting readers to contemplate the nature of time, evolution, and the fate of humanity. While the novel''s pacing may feel slow at times, and some aspects of the plot may appear dated by contemporary standards, "The Time Machine" remains a seminal work of science fiction that continues to inspire and captivate readers with its timeless themes and imaginative vision.')
