-- Drop and recreate book lists table
DROP TABLE IF EXISTS book_lists CASCADE;

CREATE TABLE book_lists (
  id SERIAL PRIMARY KEY NOT NULL,
  --book_author_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
  book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
  list_id INTEGER NOT NULL REFERENCES lists(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);